### PR TITLE
feat: added DD logs and rum config

### PR DESCRIPTION
**Pull request by abdullahwaheed**

### CODE REVIEW

**Comment by adamstankiewicz** [comment]
@waheedahmed I'm going to close this PR as we have taken a different, more open-source friendly approach to adding Datadog logs and RUM for the 2U-hosted MFEs. Let me know if you have any concerns around closing the PR, thanks! :)

**Comment by waheedahmed** [comment]
@adamstankiewicz I guess you wanted to tag @abdullahwaheed here 😄

**Comment by adamstankiewicz** [comment]
> @adamstankiewicz I guess you wanted to tag @abdullahwaheed here 😄

D'oh, yep... apologies for the errant ping!

**Comment by waheedahmed** [comment]
No worries 🙂

**Pull request closed without merging**
