### PR TITLE
feat: updated jest to v29

### PR DESCRIPTION
**Pull request by BilalQamar95**
# Description
- Updated jest to resolve [word-wrap ReDoS vulnerability](https://github.com/openedx/frontend-build/security/dependabot/38), along with other minor package upgrades
- Updated `jest` config for v29 ([ChangeLog details](https://openedx.atlassian.net/wiki/spaces/AC/pages/3825008641/Jest+upgrade+from+v26+to+v29))

# Breaking Change:
Updating jest from v26 to v29 introduces breaking change (except dropping Node versions), and that is to default [snapshotFormat](https://jestjs.io/docs/configuration#snapshotformat-object) to {escapeString: false, printBasicPrototype: false}. This makes snapshots both more readable and more copy-pasteable.

### CODE REVIEW

**Comment by brian-smith-tcril** [comment]
Has this been tested against any MFEs? If so, could you link draft PRs to those MFEs with this branch (or a branch created based on this branch with `dist` checked in) installed via git instead of npm?

Having a couple MFEs verified working (and knowing what issues arose in the process of making them work) will go a long way towards creating "how to upgrade your MFE to use jest v29" documentation.

**Comment by arbrandes** [comment]
As per an internal conversation with @brian-smith-tcril, one way we could handle major upgrades to base libraries like this one is to start issuing bugfixes to the previous version, so there's (somewhat) less urgency in upgrading all downstream users.

Apparently, semantic-release provides for this rather neatly:  https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/maintenance-releases#releasing-a-bug-fix-for-version-1.0.x-users.  We'd just need to check that this and other similar repos like paragon and frontend-platform are configured accordingly.  And, of course, to check with the corresponding maintainers if they're up to always backporting fixes.

**Comment by arbrandes** [comment]
(On the latter comment, this repo is already configured with an `alpha` pre-release branch, so we can use _that_.)

**Comment by BilalQamar95** [comment]
@brian-smith-tcril Yes, this has been tested against several MFEs with drafted PRs in all of them. Here are 2 of them which i recently updated, [frontend-app-account#958](https://github.com/openedx/frontend-app-account/pull/958) & [frontend-app-profile#932](https://github.com/openedx/frontend-app-profile/pull/932). I can update and link more if required

**Comment by brian-smith-tcril** [comment]
@BilalQamar95 the CI is failing on both of the PRs you linked.

**Comment by BilalQamar95** [comment]
> @BilalQamar95 the CI is failing on both of the PRs you linked.

That would be due to frontend-build dependency since I'm installing it from a branch, these were tested out locally, all tests are passing for both PRs. I have since added overrides for both [frontend-app-account#958](https://github.com/openedx/frontend-app-account/pull/958) & [frontend-app-profile#932](https://github.com/openedx/frontend-app-profile/pull/932) to clear out the CI, you can have a look at it again. The dependency issue for the consumers will be resolved once this PR is merged and respective drafted PRs are updated. I can update and link more PRs similarly, if required

**Comment by BilalQamar95** [comment]
@brian-smith-tcril please let me know if is there anything else I can help with in order to get this reviewed & merged

**Comment by arbrandes** [comment]
I have a question as well: should we bundle this into the alpha branch first, and release everything in one go?

**Comment by jristau1984** [comment]
> @arbrandes is there any reason to take that approach? The goal of this PR is to move the Jest upgrade forward, and bringing in other alpha-release related changes has a chance to create unnecessary noise to achieving that goal.
> 
> I am fully supportive of getting the alpha branch into main, but I think they should be considered distinct efforts.

I believe this was followed up on in the Frontend WG, and now has a path forward.

> Muhammad Abdullah Waheed Khan
in the [frontend working group](https://openedx.atlassian.net/wiki/x/AQBT9), its decided to test alpha with MFEs that do not typescript, and if it doesn't break anything other than some basic config changes, we'll merge jest with alpha and release these both simultaneously as single breaking change

**Comment by abdullahwaheed** [comment]
@arbrandes @brian-smith-tcril this PR is rebased with alpha and now ready to review and merge

**Comment by arbrandes** [comment]
@jristau1984,

>  The goal of this PR is to move the Jest upgrade forward, and bringing in other alpha-release related changes has a chance to create unnecessary noise to achieving that goal.

That's a good point, and we may still end up splitting the Typescript work from Jest 29, but there are a couple of other considerations:

* Both the Typescript (currently in `alpha`) and Jest 29 efforts result in breaking changes.  Instead of having one breaking change followed by another, I suspect it will be more efficient to handle both at once across the board.
* As I understand it, one of the blockers to getting Typescript into master is precisely Jest 29.
* The Typescript work has been parked in alpha for quite a while, now.  It's high time it either got merged to master or dropped.  If we can borrow some momentum from the Jest 29 upgrade to make a decision, so much the better.
* The alpha branch is meant to be used as a way to test breaking changes downstream before we release them (something which will come in handy for Jest 29, I'm sure), and it just so happens that Typescript is already in there.

In any case, we should revisit this strategy if we run into any blockers.

**Review by arbrandes — APPROVED** [review]
Looks good to me!  Any objections to merging this into `alpha`, @brian-smith-tcril?

**Comment by arbrandes** [comment]
Once it's in alpha, we should pick a couple of MFEs to upgrade to the `alpha` package (probably the ones that were already tested with Jest 29), and if it looks good, we go ahead with merging `alpha` to `master` here.

**Comment by arbrandes** [comment]
We should probably also have the `alpha` branches in frontend-platform, -header, and -footer churning out packages.  Let me check if they're set up properly.

**Comment by abdullahwaheed** [comment]
> We should probably also have the `alpha` branches in frontend-platform, -header, and -footer churning out packages. Let me check if they're set up properly.

We have tested account, profile and learning MFE with alpha and jest with test branches and they were working fine

**Comment by arbrandes** [comment]
Ok, see the PRs I just mentioned.  Once merged, we can make alpha packages that depend on the frontend-build alpha, and finally port at least one MFE (better a couple) to actually use them in master.  That should tell us right quick if there are any issues. :)

**Comment by arbrandes** [comment]
Alright, let's get this into `alpha`.

**Pull request merged**
