### PR TITLE
feat: add example changes for test ParagonPlugin

### PR DESCRIPTION
**Pull request by dcoa**
This is a complementary PR of  https://github.com/openedx/frontend-build/pull/546 to make changes in the example application due to the introduction of paragon and frontend-platform as dependencies.

Should be merged after the base PR

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dcoa! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
Hey @dcoa, thank you for this contribution! It looks like there are some failing tests. Could you have a look at what's happening with those?

**Comment by dcoa** [comment]
Hi @itsjeyd,  I've converted this on the draft understanding that depends on https://github.com/openedx/frontend-build/pull/546 (that's the reason for failing)

**Comment by itsjeyd** [comment]
Sounds good, thanks for the info @dcoa.

**Comment by itsjeyd** [comment]
Hi @dcoa, it looks like #546 got merged so this PR should no longer be blocked. Is that right? And will you be coming back to work on the changes in the coming days/weeks? If they're no longer needed, let me know so we can close this PR.

**Comment by dcoa** [comment]
Hi @itsjeyd,  I closed this PR understanding that the changes was introduced by https://github.com/openedx/frontend-build/pull/584 a few days ago :)

**Comment by itsjeyd** [comment]
Great, thanks @dcoa 👍

**Pull request closed without merging**
