### PR TITLE
Updated webpack-bundle-analyzer to eleminate ejs vulnnerability

### PR DESCRIPTION
**Pull request by mamankhan99**
This PR contains the following updates:

| Package | Change |
|---|---|
| ejs | [`2.7.4` -> `3.1.7`](https://renovatebot.com/diffs/npm/ejs/2.7.4/3.1.7) |

Git issues:

[chore(deps): update dependency node-forge to 1.3.0 [security]](https://github.com/openedx/frontend-app-profile/pull/520)
[chore(deps): update dependency minimist to 1.2.6 [security]](https://github.com/openedx/frontend-app-profile/pull/539)

Pre-Merge Checklist:

 Updated the version number in edx_proctoring/__init__.py and package.json if these changes are to be released.
 Described your changes in CHANGELOG.rst
 Confirmed Github reports all automated tests/checks are passing.
 Approved by at least one additional reviewer.
Post-Merge:

 Create a tag matching the new version number.

### CODE REVIEW

**Comment by natabene** [comment]
@mamankhan99 Thank you for your PR, once your forms are processed, we will review it.

**Comment by natabene** [comment]
@mamankhan99 The check is green now, so the owning team will review soon.

**Comment by davidjoy** [comment]
I think this needs to be rebased on master to resolve the conflicts.

**Comment by mamankhan99** [comment]
> I think this needs to be rebased on master to resolve the conflicts.

Done!

**Review by adamstankiewicz — APPROVED** [review]

**Pull request merged**
