### PR TITLE
build: exclude development files for npm resolves #567

### LINKED ISSUE #567: example/src/apple.svg is 2.48 MB - this is too big
The example app has a picture of an apple (example/src/apple.svg) that is 2.48 MB.  I would suggest resizing and cropping it down to a 300x300 or so picture of an Apple.  It serves as a test of how the image optimization plugins are working, and we should still be able to see a change with a much smaller file.  300x300 ought to be about 60 KB.

### PR DESCRIPTION
**Pull request by ghassanmas**
This ready for review

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dcoa** [comment]
Thank you @ghassanmas for this PR, I agree about excluding the example folder for the npm versions, however, could you explain the reasoning behind removing the apple.png image?

**Comment by ghassanmas** [comment]
> could you explain the reasoning behind removing the apple.png image 

It's not removed, but may github diff UX/UI is confusing, the file has been compressed. 

@dcoa the file/folder `example` exists, in `node_models` when you install  frontend-build as dependency, I am not sure about `files` in pacakge.json, but if npm tooling take it into considration then it could be other way to do it

**Comment by dcoa** [comment]
Apparently, during the compressing process, the file has been corrupted, that's why GitHub does not display it and the tests are not passing, could you fix that? 

Sorry for the misunderstanding, when I said "the file does not exist" I was referring to the `commitlint.config.js`.

I prefer to use `files`, in this way we have better control over what is included in the distribution version, the description about it is [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files)

**Comment by ghassanmas** [comment]
> Apparently, during the compressing process, the file has been corrupted, that's why GitHub does not display it and the tests are not passing, could you fix that?

 Oh yes just fixed it... 
 
 > Sorry for the misunderstanding, when I said "the file does not exist" I was referring to the commitlint.config.js.

 Aha true do you want to remove it, it was there from the place, may be it exists by default...

> I prefer to use files, in this way we have better control over what is included in the distribution version, the description about it is [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files) 

I see I think if use `files` then we will have to enter everything, right? which make the array too large

**Comment by dcoa** [comment]
> I see I think if use files then we will have to enter everything, right? which make the array too large

I don't think the array gets large, it is these ones

```JSON
  "files": [
    "/bin",
    "/config",
    "/lib",
    "tsconfig.json"
  ],
```

If we use the `npmignore` file, can we increase the scope of this PR not only to exclude the example folder but also these:

- renovate.json
- coverage
- lib/**/tests
- docs
- .github
- smoke-test.sh
- .eslintignore
- .eslintrc.js
- .nvmrc

This way, we can push only the relevant files for the consumer application.

**Comment by ghassanmas** [comment]
yes right, we need to exclude other files/directory beside, `example`. I deleted the `.npmignore` file. 
Note, by default npm will ignore everything in `.gitignore`.

**Comment by dcoa** [comment]
Thanks @ghassanmas, LGTM!!

**Review by dcoa — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-build&entry.867055334=https://github.com/openedx/frontend-build/pull/568&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2024-07-09+21:40&entry.1917517419=2024-07-19+21:33&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
