### PR TITLE
feat: add eslint role for no message description

### PR DESCRIPTION
**Pull request by ghassanmas**
This uses an eslint role for getting strings with no
  descriptions, this for demonstration purpose and can be used
  for checking other MFEs or JS/React base repos

  Ref: openedx/wg-translations/issues/5
  Related discussion: openedx/frontend-app-learning/pull/1143

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hey @ghassanmas, just checking in to see if you're still planning to come back to this PR?

**Comment by itsjeyd** [comment]
Hi @ghassanmas! Just a quick update that we're closing this PR now because it seems to have become stale. You may reopen this pull request, or open a new one, when you have time to come back to this work.

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-build&entry.867055334=https://github.com/openedx/frontend-build/pull/460&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-09-27+17:33&entry.1917517419=2023-11-23+13:26&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@ghassanmas Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-build&entry.867055334=https://github.com/openedx/frontend-build/pull/460&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2023-09-27+17:33&entry.1917517419=2023-11-23+13:26&entry.2133058324=No) so we can improve your experience in the future.

**Comment by ghassanmas** [comment]
@itsjeyd I would be happy to continue wokring on resolving the conflicts, if there would a guarantee that this changes/ PR would be accepted at somepoint. This is just to avoid spending time on someting that might not be accepted. I think following https://github.com/openedx/frontend-app-learning/pull/1143, @brian-smith-tcril might have a say on that.

**Comment by itsjeyd** [comment]
OSPR management note: See https://github.com/openedx/wg-translations/issues/5#issuecomment-1948538346 for latest status. (This PR is still blocked waiting for general confirmation about whether it has a chance of being accepted at some point.)

CC @ehuthmacher

**Comment by brian-smith-tcril** [comment]
I discussed this with the Axim team and we decided a change like this will need to include a plan for all the consumers of `frontend-build` to support the new eslint rule. I have opened a PR https://github.com/openedx/frontend-build/pull/516 creating an alternate eslint config (`eslint-next`) that can be pulled in to MFEs using `createConfig('eslint-next', {` (example here https://github.com/openedx/frontend-app-learning/pull/1319)

This will allow us to migrate applications that depend on `frontend-build` over (and add descriptions to the source strings) without breaking their ability to upgrade `frontend-build`.

I've created an issue laying out the high level plan https://github.com/openedx/frontend-build/issues/517

**Pull request closed without merging**
